services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8000:3000"
    volumes:
      - "./frontend:/opt/app"
    environment:
      - "CI=true"
    restart: always
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - "./backend:/opt/app"
    restart: always
