services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: always
